<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Default suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Default test(failed)">
    <classes>
<<<<<<< HEAD
      <class name="AutomationFramework.tests.ErrorValidationTest">
        <methods>
          <include name="incorrectCreds"/>
          <include name="teardown"/>
          <include name="launchapp"/>
        </methods>
      </class> <!-- AutomationFramework.tests.ErrorValidationTest -->
=======
      <class name="AutomationFramework.tests.SubmitorderTest">
        <methods>
          <include name="Verifyorder"/>
          <include name="teardown"/>
          <include name="submitorder" invocation-numbers="1"/>
          <include name="launchapp"/>
        </methods>
      </class> <!-- AutomationFramework.tests.SubmitorderTest -->
>>>>>>> 2760f21 (Handled Exception code)
    </classes>
  </test> <!-- Default test(failed) -->
</suite> <!-- Failed suite [Default suite] -->
