<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="DESKTOP-6BCGIB4" failures="0" tests="4" name="Submit order Test" time="47.03" errors="0" timestamp="2025-02-08T19:00:08 IST">
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="17.811"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="13.62"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="0.788"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="0.792"/>
=======
<testsuite ignored="0" hostname="WS-19080" failures="0" tests="4" name="Submit order Test" time="36.758" errors="0" timestamp="2025-02-09T21:19:37 IST">
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="13.512"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="submitorder" time="13.419"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="0.712"/>
  <testcase classname="AutomationFramework.tests.SubmitorderTest" name="Verifyorder" time="0.675"/>
>>>>>>> 2760f21 (Handled Exception code)
</testsuite> <!-- Submit order Test -->
